var mongoose    = require('mongoose');
var config      = require('./config/database'); // get db config file
var srpschema   = require('./app/models/userdone');
var port        = process.env.PORT || 9000;
mongoose.connect(config.database);

function makeid() {
  var text = "";
  var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

  for (var i = 0; i < 8; i++)
    text += possible.charAt(Math.floor(Math.random() * possible.length));

  return text;
}


new srpschema({_id :"5003",name:"Aishwarya Devi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5004",name:"Ajitaajagannathan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5005",name:"Ambareesh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5006",name:"Anandhi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5007",name:"Arsvhardhenee",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5008",name:"Aswin",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5009",name:"Balaji",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5010",name:"Bharathi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5011",name:"Deshali",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5012",name:"Durga Devi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5013",name:"Gokul",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5014",name:"Gowtham",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5015",name:"Harani Sri Reka",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5016",name:"Heera",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5017",name:"Iswarya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5018",name:"Janani",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5020",name:"Kaliappan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5021",name:"Karthik",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5023",name:"Keerthana",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5025",name:"Lavanya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5026",name:"Mageshwaran",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5027",name:"Manisha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5028",name:"Mithra",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5029",name:"Mohammed Asif",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5030",name:"Monisha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5031",name:"Munavar Sherif",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5032",name:"Nandha Kumar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5033",name:"Nisha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5034",name:"Nivethika",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5035",name:"Pavithra",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5036",name:"Pooja Shree",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5037",name:"Poorna",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5038",name:"Prasadh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5039",name:"Prashanth Lidwin Jessuva",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5041",name:"Preeti",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5042",name:"Raaghavi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5043",name:"Raja Pandiyan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5044",name:"Raj Kumar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5045",name:"Rohit",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5046",name:"Santhosh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5047",name:"Saravana Vignesh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5048",name:"Saravanan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5049",name:"Sarguru",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5050",name:"Selva Kumar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5051",name:"Shanmugapriya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5053",name:"Shrivijay",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5054",name:"Soundarya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5055",name:"Sruthi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5056",name:"Suganthy",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5057",name:"Surya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5058",name:"Uma",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5059",name:"Vinotha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5060",name:"Yuvraj",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5061",name:"Aarthi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5063",name:"Ajay Hayagreeve",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5064",name:"Akalya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5065",name:"Amruthaa Varshini",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5066",name:"Areefkhan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5067",name:"Aruna",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5068",name:"Bala Sekar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5069",name:"Benny Kiwin Cardoza",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5070",name:"David Sundara Raj ",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5071",name:"Divya Bharathi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5072",name:"Geetha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5073",name:"Gousalya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5074",name:"Hari",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5075",name:"Haripriya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5076",name:"Hemalatha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5077",name:"Janani Dharshana",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5078",name:"Jaya Bharathi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5079",name:"Jemima",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5080",name:"Kalki",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5081",name:"Katnal Rajarao",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5082",name:"Kavya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5083",name:"Krishna Raj ",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5084",name:"Kumaragurubaran",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5085",name:"Madhumitha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5086",name:"Manimozhoi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5087",name:"Maruthamani",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5088",name:"Mohammed Bilal",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5089",name:"Mohan Raj",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5090",name:"Mosikiran",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5091",name:"Mythili",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5092",name:"Nandhini",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5093",name:"Nithya Priya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5094",name:"Pauljudith",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5096",name:"Poorani",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5097",name:"Praburaj",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5098",name:"Prasathth",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5100",name:"Pravin Vignesh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5101",name:"Priyanka",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5102",name:"Raiyan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5104",name:"Ranjini",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5105",name:"Sanshitha",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5106",name:"Saranya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5107",name:"Saravanaganesh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5108",name:"Sardaus Lifra",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5109",name:"Sasidaran",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5110",name:"Shamili",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5111",name:"Sharmila",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5112",name:"Shree Dhanvi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5113",name:"Soundarya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}});
new srpschema({_id :"5114",name:"Sri Nathi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5115",name:"Ssherya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5116",name:"Surendhar Kumar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5117",name:"Udaya Ram Kumar",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5118",name:"Venkatesh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5119",name:"Yoga Lakshmi",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5120",name:"Suraj Kumar Singh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5121",name:"Atluri Saisowmya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5122",name:"Aishwarya",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5124",name:"Arvindh",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 
new srpschema({_id :"5125",name:"Sabarimukilan",year:"4",password:makeid(),childpic:"0",firsttime:"1"}).save(function(err, doc){if(err) {console.log(err);}}); 

console.log("Done")